### ISSUE TITLE
-ppl argument in w3m:w3m-rendering-half-dump is not supported by w3m.exe 0.5.3 on windows

### ISSUE THREAD

**Issue by md11235** [ecbrown/emacs-w3m#1]
Both w3m.exe in cygwin and msys2 does not work because it does not support the "-ppl" option.

After reviewing the source code for w3m itself:

#ifdef USE_IMAGE
	    else if (!strcmp("-ppl", argv[i])) {
		double ppc;
		if (++i >= argc)
		    usage();
		ppc = atof(argv[i]);
		if (ppc >= MINIMUM_PIXEL_PER_CHAR &&
		    ppc <= MAXIMUM_PIXEL_PER_CHAR * 2) {
		    pixel_per_line = ppc;
		    set_pixel_per_line = TRUE;
		}
	    }
#endif

So it seems the "-ppl" option is not enabled for windows built.

Could this problem be solved for emacs and emacs-w3m users on windows?

Thank you very much!

**Comment by ecbrown** [comment]
Thanks for the report.  This GitHub repository is merely a git clone of the CVS repository, and I would recommend that you submit your patch to:

http://emacs-w3m.namazu.org
